import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc

# Define plot settings
rc('font', **{'family': 'serif', 'serif': ['Palatino'], 'size': 13})
plt.rcParams['pdf.fonttype'] = 42
plt.rcParams['ps.fonttype'] = 42
plt.rcParams["figure.dpi"] = 200

#%% Load Single Rl Data
S4_results = np.load("checkpoints/single_agent/four_stage/results.npy")
S4_time = np.load("checkpoints/single_agent/four_stage/time.npy")
S4_reward_mean = np.load("checkpoints/single_agent/four_stage/reward_mean.npy")
S4_reward_std = np.load("checkpoints/single_agent/four_stage/reward_std.npy")
S4_inventory_mean = np.load("checkpoints/single_agent/four_stage/inventory_mean.npy")
S4_inventory_std = np.load("checkpoints/single_agent/four_stage/inventory_std.npy")
S4_backlog_mean = np.load("checkpoints/single_agent/four_stage/backlog_mean.npy")
S4_backlog_std = np.load("checkpoints/single_agent/four_stage/backlog_std.npy")
S4_customer_backlog_mean = np.load("checkpoints/single_agent/four_stage/customer_backlog_mean.npy")
S4_customer_backlog_std = np.load("checkpoints/single_agent/four_stage/customer_backlog_std.npy")
S4_profit = np.load("checkpoints/single_agent/four_stage/profit.npy")

S2_results = np.load("checkpoints/single_agent/two_stage/results.npy")
S2_time = np.load("checkpoints/single_agent/two_stage/time.npy")
S2_reward_mean = np.load("checkpoints/single_agent/two_stage/reward_mean.npy")
S2_reward_std = np.load("checkpoints/single_agent/two_stage/reward_std.npy")
S2_inventory_mean = np.load("checkpoints/single_agent/two_stage/inventory_mean.npy")
S2_inventory_std = np.load("checkpoints/single_agent/two_stage/inventory_std.npy")
S2_backlog_mean = np.load("checkpoints/single_agent/two_stage/backlog_mean.npy")
S2_backlog_std = np.load("checkpoints/single_agent/two_stage/backlog_std.npy")
S2_customer_backlog_mean = np.load("checkpoints/single_agent/two_stage/customer_backlog_mean.npy")
S2_customer_backlog_std = np.load("checkpoints/single_agent/two_stage/customer_backlog_std.npy")
S2_profit = np.load("checkpoints/single_agent/two_stage/profit.npy")

S8_results = np.load("checkpoints/single_agent/eight_stage/results.npy")
S8_time = np.load("checkpoints/single_agent/eight_stage/time.npy")
S8_reward_mean = np.load("checkpoints/single_agent/eight_stage/reward_mean.npy")
S8_reward_std = np.load("checkpoints/single_agent/eight_stage/reward_std.npy")
S8_inventory_mean = np.load("checkpoints/single_agent/eight_stage/inventory_mean.npy")
S8_inventory_std = np.load("checkpoints/single_agent/eight_stage/inventory_std.npy")
S8_backlog_mean = np.load("checkpoints/single_agent/eight_stage/backlog_mean.npy")
S8_backlog_std = np.load("checkpoints/single_agent/eight_stage/backlog_std.npy")
S8_customer_backlog_mean = np.load("checkpoints/single_agent/eight_stage/customer_backlog_mean.npy")
S8_customer_backlog_std = np.load("checkpoints/single_agent/eight_stage/customer_backlog_std.npy")
S8_profit = np.load("checkpoints/single_agent/eight_stage/profit.npy")

S4N2_results = np.load("checkpoints/single_agent/four_stage_noise_2/results.npy")
S4N2_time = np.load("checkpoints/single_agent/four_stage_noise_2/time.npy")
S4N2_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_2/reward_mean.npy")
S4N2_reward_std = np.load("checkpoints/single_agent/four_stage_noise_2/reward_std.npy")
S4N2_inventory_mean = np.load("checkpoints/single_agent/four_stage_noise_2/inventory_mean.npy")
S4N2_inventory_std = np.load("checkpoints/single_agent/four_stage_noise_2/inventory_std.npy")
S4N2_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_2/backlog_mean.npy")
S4N2_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_2/backlog_std.npy")
S4N2_customer_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_2/customer_backlog_mean.npy")
S4N2_customer_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_2/customer_backlog_std.npy")
S4N2_profit = np.load("checkpoints/single_agent/four_stage_noise_2/profit.npy")

S4N5_results = np.load("checkpoints/single_agent/four_stage_noise_5/results.npy")
S4N5_time = np.load("checkpoints/single_agent/four_stage_noise_5/time.npy")
S4N5_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_5/reward_mean.npy")
S4N5_reward_std = np.load("checkpoints/single_agent/four_stage_noise_5/reward_std.npy")
S4N5_inventory_mean = np.load("checkpoints/single_agent/four_stage_noise_5/inventory_mean.npy")
S4N5_inventory_std = np.load("checkpoints/single_agent/four_stage_noise_5/inventory_std.npy")
S4N5_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_5/backlog_mean.npy")
S4N5_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_5/backlog_std.npy")
S4N5_customer_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_5/customer_backlog_mean.npy")
S4N5_customer_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_5/customer_backlog_std.npy")
S4N5_profit = np.load("checkpoints/single_agent/four_stage_noise_5/profit.npy")

S4N10_results = np.load("checkpoints/single_agent/four_stage_noise_10/results.npy")
S4N10_time = np.load("checkpoints/single_agent/four_stage_noise_10/time.npy")
S4N10_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_10/reward_mean.npy")
S4N10_reward_std = np.load("checkpoints/single_agent/four_stage_noise_10/reward_std.npy")
S4N10_inventory_mean = np.load("checkpoints/single_agent/four_stage_noise_10/inventory_mean.npy")
S4N10_inventory_std = np.load("checkpoints/single_agent/four_stage_noise_10/inventory_std.npy")
S4N10_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_10/backlog_mean.npy")
S4N10_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_10/backlog_std.npy")
S4N10_customer_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_10/customer_backlog_mean.npy")
S4N10_customer_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_10/customer_backlog_std.npy")
S4N10_profit = np.load("checkpoints/single_agent/four_stage_noise_10/profit.npy")

S4N20_results = np.load("checkpoints/single_agent/four_stage_noise_20/results.npy")
S4N20_time = np.load("checkpoints/single_agent/four_stage_noise_20/time.npy")
S4N20_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_20/reward_mean.npy")
S4N20_reward_std = np.load("checkpoints/single_agent/four_stage_noise_20/reward_std.npy")
S4N20_inventory_mean = np.load("checkpoints/single_agent/four_stage_noise_20/inventory_mean.npy")
S4N20_inventory_std = np.load("checkpoints/single_agent/four_stage_noise_20/inventory_std.npy")
S4N20_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_20/backlog_mean.npy")
S4N20_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_20/backlog_std.npy")
S4N20_customer_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_20/customer_backlog_mean.npy")
S4N20_customer_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_20/customer_backlog_std.npy")
S4N20_profit = np.load("checkpoints/single_agent/four_stage_noise_20/profit.npy")

S4N50_results = np.load("checkpoints/single_agent/four_stage_noise_50/results.npy")
S4N50_time = np.load("checkpoints/single_agent/four_stage_noise_50/time.npy")
S4N50_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_50/reward_mean.npy")
S4N50_reward_std = np.load("checkpoints/single_agent/four_stage_noise_50/reward_std.npy")
S4N50_inventory_mean = np.load("checkpoints/single_agent/four_stage_noise_50/inventory_mean.npy")
S4N50_inventory_std = np.load("checkpoints/single_agent/four_stage_noise_50/inventory_std.npy")
S4N50_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_50/backlog_mean.npy")
S4N50_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_50/backlog_std.npy")
S4N50_customer_backlog_mean = np.load("checkpoints/single_agent/four_stage_noise_50/customer_backlog_mean.npy")
S4N50_customer_backlog_std = np.load("checkpoints/single_agent/four_stage_noise_50/customer_backlog_std.npy")
S4N50_profit = np.load("checkpoints/single_agent/four_stage_noise_50/profit.npy")

#%% Load MA Rl Data
MA4_results = np.load("checkpoints/multi_agent/four_stage/results.npy")
MA4_time = np.load("checkpoints/multi_agent/four_stage/time.npy")
MA4_reward_mean = np.load("checkpoints/multi_agent/four_stage/reward_mean.npy")
MA4_reward_std = np.load("checkpoints/multi_agent/four_stage/reward_std.npy")
MA4_inventory_mean = np.load("checkpoints/multi_agent/four_stage/inventory_mean.npy")
MA4_inventory_std = np.load("checkpoints/multi_agent/four_stage/inventory_std.npy")
MA4_backlog_mean = np.load("checkpoints/multi_agent/four_stage/backlog_mean.npy")
MA4_backlog_std = np.load("checkpoints/multi_agent/four_stage/backlog_std.npy")
MA4_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage/customer_backlog_mean.npy")
MA4_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage/customer_backlog_std.npy")
MA4_profit = np.load("checkpoints/multi_agent/four_stage/profit.npy")

MA4I_results = np.load("checkpoints/multi_agent/four_stage_independent/results.npy")
MA4I_time = np.load("checkpoints/multi_agent/four_stage_independent/time.npy")
MA4I_reward_mean = np.load("checkpoints/multi_agent/four_stage_independent/reward_mean.npy")
MA4I_reward_std = np.load("checkpoints/multi_agent/four_stage_independent/reward_std.npy")
MA4i_inventory_mean = np.load("checkpoints/multi_agent/four_stage_independent/inventory_mean.npy")
MA4I_inventory_std = np.load("checkpoints/multi_agent/four_stage_independent/inventory_std.npy")
MA4I_backlog_mean = np.load("checkpoints/multi_agent/four_stage_independent/backlog_mean.npy")
MA4I_backlog_std = np.load("checkpoints/multi_agent/four_stage_independent/backlog_std.npy")
MA4I_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_independent/customer_backlog_mean.npy")
MA4I_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_independent/customer_backlog_std.npy")
MA4I_profit = np.load("checkpoints/multi_agent/four_stage_independent/profit.npy")

MA2_results = np.load("checkpoints/multi_agent/two_stage/results.npy")
MA2_time = np.load("checkpoints/multi_agent/two_stage/time.npy")
MA2_reward_mean = np.load("checkpoints/multi_agent/two_stage/reward_mean.npy")
MA2_reward_std = np.load("checkpoints/multi_agent/two_stage/reward_std.npy")
MA2_inventory_mean = np.load("checkpoints/multi_agent/two_stage/inventory_mean.npy")
MA2_inventory_std = np.load("checkpoints/multi_agent/two_stage/inventory_std.npy")
MA2_backlog_mean = np.load("checkpoints/multi_agent/two_stage/backlog_mean.npy")
MA2_backlog_std = np.load("checkpoints/multi_agent/two_stage/backlog_std.npy")
MA2_customer_backlog_mean = np.load("checkpoints/multi_agent/two_stage/customer_backlog_mean.npy")
MA2_customer_backlog_std = np.load("checkpoints/multi_agent/two_stage/customer_backlog_std.npy")
MA2_profit = np.load("checkpoints/multi_agent/two_stage/profit.npy")

MA8_results = np.load("checkpoints/multi_agent/eight_stage/results.npy")
MA8_time = np.load("checkpoints/multi_agent/eight_stage/time.npy")
MA8_reward_mean = np.load("checkpoints/multi_agent/eight_stage/reward_mean.npy")
MA8_reward_std = np.load("checkpoints/multi_agent/eight_stage/reward_std.npy")
MA8_inventory_mean = np.load("checkpoints/multi_agent/eight_stage/inventory_mean.npy")
MA8_inventory_std = np.load("checkpoints/multi_agent/eight_stage/inventory_std.npy")
MA8_backlog_mean = np.load("checkpoints/multi_agent/eight_stage/backlog_mean.npy")
MA8_backlog_std = np.load("checkpoints/multi_agent/eight_stage/backlog_std.npy")
MA8_customer_backlog_mean = np.load("checkpoints/multi_agent/eight_stage/customer_backlog_mean.npy")
MA8_customer_backlog_std = np.load("checkpoints/multi_agent/eight_stage/customer_backlog_std.npy")
MA8_profit = np.load("checkpoints/multi_agent/eight_stage/profit.npy")

MA4N2_results = np.load("checkpoints/multi_agent/four_stage_noise_2/results.npy")
MA4N2_time = np.load("checkpoints/multi_agent/four_stage_noise_2/time.npy")
MA4N2_reward_mean = np.load("checkpoints/multi_agent/four_stage_noise_2/reward_mean.npy")
MA4N2_reward_std = np.load("checkpoints/multi_agent/four_stage_noise_2/reward_std.npy")
MA4N2_inventory_mean = np.load("checkpoints/multi_agent/four_stage_noise_2/inventory_mean.npy")
MA4N2_inventory_std = np.load("checkpoints/multi_agent/four_stage_noise_2/inventory_std.npy")
MA4N2_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_2/backlog_mean.npy")
MA4N2_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_2/backlog_std.npy")
MA4N2_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_2/customer_backlog_mean.npy")
MA4N2_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_2/customer_backlog_std.npy")
MA4N2_profit = np.load("checkpoints/multi_agent/four_stage_noise_2/profit.npy")

MA4N5_results = np.load("checkpoints/multi_agent/four_stage_noise_5/results.npy")
MA4N5_time = np.load("checkpoints/multi_agent/four_stage_noise_5/time.npy")
MA4N5_reward_mean = np.load("checkpoints/multi_agent/four_stage_noise_5/reward_mean.npy")
MA4N5_reward_std = np.load("checkpoints/multi_agent/four_stage_noise_5/reward_std.npy")
MA4N5_inventory_mean = np.load("checkpoints/multi_agent/four_stage_noise_5/inventory_mean.npy")
MA4N5_inventory_std = np.load("checkpoints/multi_agent/four_stage_noise_5/inventory_std.npy")
MA4N5_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_5/backlog_mean.npy")
MA4N5_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_5/backlog_std.npy")
MA4N5_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_5/customer_backlog_mean.npy")
MA4N5_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_5/customer_backlog_std.npy")
MA4N5_profit = np.load("checkpoints/multi_agent/four_stage_noise_5/profit.npy")

MA4N10_results = np.load("checkpoints/multi_agent/four_stage_noise_10/results.npy")
MA4N10_time = np.load("checkpoints/multi_agent/four_stage_noise_10/time.npy")
MA4N10_reward_mean = np.load("checkpoints/multi_agent/four_stage_noise_10/reward_mean.npy")
MA4N10_reward_std = np.load("checkpoints/multi_agent/four_stage_noise_10/reward_std.npy")
MA4N10_inventory_mean = np.load("checkpoints/multi_agent/four_stage_noise_10/inventory_mean.npy")
MA4N10_inventory_std = np.load("checkpoints/multi_agent/four_stage_noise_10/inventory_std.npy")
MA4N10_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_10/backlog_mean.npy")
MA4N10_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_10/backlog_std.npy")
MA4N10_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_10/customer_backlog_mean.npy")
MA4N10_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_10/customer_backlog_std.npy")
MA4N10_profit = np.load("checkpoints/multi_agent/four_stage_noise_10/profit.npy")

MA4N20_results = np.load("checkpoints/multi_agent/four_stage_noise_20/results.npy")
MA4N20_time = np.load("checkpoints/multi_agent/four_stage_noise_20/time.npy")
MA4N20_reward_mean = np.load("checkpoints/multi_agent/four_stage_noise_20/reward_mean.npy")
MA4N20_reward_std = np.load("checkpoints/multi_agent/four_stage_noise_20/reward_std.npy")
MA4N20_inventory_mean = np.load("checkpoints/multi_agent/four_stage_noise_20/inventory_mean.npy")
MA4N20_inventory_std = np.load("checkpoints/multi_agent/four_stage_noise_20/inventory_std.npy")
MA4N20_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_20/backlog_mean.npy")
MA4N20_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_20/backlog_std.npy")
MA4N20_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_20/customer_backlog_mean.npy")
MA4N20_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_20/customer_backlog_std.npy")
MA4N20_profit = np.load("checkpoints/multi_agent/four_stage_noise_20/profit.npy")

MA4N50_results = np.load("checkpoints/multi_agent/four_stage_noise_50/results.npy")
MA4N50_time = np.load("checkpoints/multi_agent/four_stage_noise_50/time.npy")
MA4N50_reward_mean = np.load("checkpoints/multi_agent/four_stage_noise_50/reward_mean.npy")
MA4N50_reward_std = np.load("checkpoints/multi_agent/four_stage_noise_50/reward_std.npy")
MA4N50_inventory_mean = np.load("checkpoints/multi_agent/four_stage_noise_50/inventory_mean.npy")
MA4N50_inventory_std = np.load("checkpoints/multi_agent/four_stage_noise_50/inventory_std.npy")
MA4N50_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_50/backlog_mean.npy")
MA4N50_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_50/backlog_std.npy")
MA4N50_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_noise_50/customer_backlog_mean.npy")
MA4N50_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_noise_50/customer_backlog_std.npy")
MA4N50_profit = np.load("checkpoints/multi_agent/four_stage_noise_50/profit.npy")

#%% Load MA Shared Rl Data
MAS4_results = np.load("checkpoints/multi_agent/four_stage_share/results.npy")
MAS4_time = np.load("checkpoints/multi_agent/four_stage_share/time.npy")
MAS4_reward_mean = np.load("checkpoints/multi_agent/four_stage_share/reward_mean.npy")
MAS4_reward_std = np.load("checkpoints/multi_agent/four_stage_share/reward_std.npy")
MAS4_inventory_mean = np.load("checkpoints/multi_agent/four_stage_share/inventory_mean.npy")
MAS4_inventory_std = np.load("checkpoints/multi_agent/four_stage_share/inventory_std.npy")
MAS4_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share/backlog_mean.npy")
MAS4_backlog_std = np.load("checkpoints/multi_agent/four_stage_share/backlog_std.npy")
MAS4_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share/customer_backlog_mean.npy")
MAS4_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_share/customer_backlog_std.npy")
MAS4_profit = np.load("checkpoints/multi_agent/four_stage_share/profit.npy")

MAS4I_results = np.load("checkpoints/multi_agent/four_stage_share_independent/results.npy")
MAS4I_time = np.load("checkpoints/multi_agent/four_stage_share_independent/time.npy")
MAS4I_reward_mean = np.load("checkpoints/multi_agent/four_stage_share_independent/reward_mean.npy")
MAS4I_reward_std = np.load("checkpoints/multi_agent/four_stage_share_independent/reward_std.npy")
MAS4i_inventory_mean = np.load("checkpoints/multi_agent/four_stage_share_independent/inventory_mean.npy")
MAS4I_inventory_std = np.load("checkpoints/multi_agent/four_stage_share_independent/inventory_std.npy")
MAS4I_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_independent/backlog_mean.npy")
MAS4I_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_independent/backlog_std.npy")
MAS4I_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_independent/customer_backlog_mean.npy")
MAS4I_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_independent/customer_backlog_std.npy")
MAS4I_profit = np.load("checkpoints/multi_agent/four_stage_share_independent/profit.npy")

MA2_results = np.load("checkpoints/multi_agent/two_stage_share/results.npy")
MA2_time = np.load("checkpoints/multi_agent/two_stage_share/time.npy")
MA2_reward_mean = np.load("checkpoints/multi_agent/two_stage_share/reward_mean.npy")
MA2_reward_std = np.load("checkpoints/multi_agent/two_stage_share/reward_std.npy")
MA2_inventory_mean = np.load("checkpoints/multi_agent/two_stage_share/inventory_mean.npy")
MA2_inventory_std = np.load("checkpoints/multi_agent/two_stage_share/inventory_std.npy")
MA2_backlog_mean = np.load("checkpoints/multi_agent/two_stage_share/backlog_mean.npy")
MA2_backlog_std = np.load("checkpoints/multi_agent/two_stage_share/backlog_std.npy")
MA2_customer_backlog_mean = np.load("checkpoints/multi_agent/two_stage_share/customer_backlog_mean.npy")
MA2_customer_backlog_std = np.load("checkpoints/multi_agent/two_stage_share/customer_backlog_std.npy")
MA2_profit = np.load("checkpoints/multi_agent/two_stage_share/profit.npy")

MAS8_results = np.load("checkpoints/multi_agent/eight_stage_share/results.npy")
MAS8_time = np.load("checkpoints/multi_agent/eight_stage_share/time.npy")
MAS8_reward_mean = np.load("checkpoints/multi_agent/eight_stage_share/reward_mean.npy")
MAS8_reward_std = np.load("checkpoints/multi_agent/eight_stage_share/reward_std.npy")
MAS8_inventory_mean = np.load("checkpoints/multi_agent/eight_stage_share/inventory_mean.npy")
MAS8_inventory_std = np.load("checkpoints/multi_agent/eight_stage_share/inventory_std.npy")
MAS8_backlog_mean = np.load("checkpoints/multi_agent/eight_stage_share/backlog_mean.npy")
MAS8_backlog_std = np.load("checkpoints/multi_agent/eight_stage_share/backlog_std.npy")
MAS8_customer_backlog_mean = np.load("checkpoints/multi_agent/eight_stage_share/customer_backlog_mean.npy")
MAS8_customer_backlog_std = np.load("checkpoints/multi_agent/eight_stage_share/customer_backlog_std.npy")
MAS8_profit = np.load("checkpoints/multi_agent/eight_stage_share/profit.npy")

MAS4N2_results = np.load("checkpoints/multi_agent/four_stage_share_noise_2/results.npy")
MAS4N2_time = np.load("checkpoints/multi_agent/four_stage_share_noise_2/time.npy")
MAS4N2_reward_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_2/reward_mean.npy")
MAS4N2_reward_std = np.load("checkpoints/multi_agent/four_stage_share_noise_2/reward_std.npy")
MAS4N2_inventory_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_2/inventory_mean.npy")
MAS4N2_inventory_std = np.load("checkpoints/multi_agent/four_stage_share_noise_2/inventory_std.npy")
MAS4N2_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_2/backlog_mean.npy")
MAS4N2_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_2/backlog_std.npy")
MAS4N2_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_2/customer_backlog_mean.npy")
MAS4N2_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_2/customer_backlog_std.npy")
MAS4N2_profit = np.load("checkpoints/multi_agent/four_stage_share_noise_2/profit.npy")

MAS4N5_results = np.load("checkpoints/multi_agent/four_stage_share_noise_5/results.npy")
MAS4N5_time = np.load("checkpoints/multi_agent/four_stage_share_noise_5/time.npy")
MAS4N5_reward_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_5/reward_mean.npy")
MAS4N5_reward_std = np.load("checkpoints/multi_agent/four_stage_share_noise_5/reward_std.npy")
MAS4N5_inventory_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_5/inventory_mean.npy")
MAS4N5_inventory_std = np.load("checkpoints/multi_agent/four_stage_share_noise_5/inventory_std.npy")
MAS4N5_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_5/backlog_mean.npy")
MAS4N5_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_5/backlog_std.npy")
MAS4N5_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_5/customer_backlog_mean.npy")
MAS4N5_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_5/customer_backlog_std.npy")
MAS4N5_profit = np.load("checkpoints/multi_agent/four_stage_share_noise_5/profit.npy")

MAS4N10_results = np.load("checkpoints/multi_agent/four_stage_share_noise_10/results.npy")
MAS4N10_time = np.load("checkpoints/multi_agent/four_stage_share_noise_10/time.npy")
MAS4N10_reward_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_10/reward_mean.npy")
MAS4N10_reward_std = np.load("checkpoints/multi_agent/four_stage_share_noise_10/reward_std.npy")
MAS4N10_inventory_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_10/inventory_mean.npy")
MAS4N10_inventory_std = np.load("checkpoints/multi_agent/four_stage_share_noise_10/inventory_std.npy")
MAS4N10_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_10/backlog_mean.npy")
MAS4N10_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_10/backlog_std.npy")
MAS4N10_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_10/customer_backlog_mean.npy")
MAS4N10_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_10/customer_backlog_std.npy")
MAS4N10_profit = np.load("checkpoints/multi_agent/four_stage_share_noise_10/profit.npy")

MAS4N20_results = np.load("checkpoints/multi_agent/four_stage_share_noise_20/results.npy")
MAS4N20_time = np.load("checkpoints/multi_agent/four_stage_share_noise_20/time.npy")
MAS4N20_reward_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_20/reward_mean.npy")
MAS4N20_reward_std = np.load("checkpoints/multi_agent/four_stage_share_noise_20/reward_std.npy")
MAS4N20_inventory_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_20/inventory_mean.npy")
MAS4N20_inventory_std = np.load("checkpoints/multi_agent/four_stage_share_noise_20/inventory_std.npy")
MAS4N20_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_20/backlog_mean.npy")
MAS4N20_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_20/backlog_std.npy")
MAS4N20_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_20/customer_backlog_mean.npy")
MAS4N20_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_20/customer_backlog_std.npy")
MAS4N20_profit = np.load("checkpoints/multi_agent/four_stage_share_noise_20/profit.npy")

MAS4N50_results = np.load("checkpoints/multi_agent/four_stage_share_noise_50/results.npy")
MAS4N50_time = np.load("checkpoints/multi_agent/four_stage_share_noise_50/time.npy")
MAS4N50_reward_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_50/reward_mean.npy")
MAS4N50_reward_std = np.load("checkpoints/multi_agent/four_stage_share_noise_50/reward_std.npy")
MAS4N50_inventory_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_50/inventory_mean.npy")
MAS4N50_inventory_std = np.load("checkpoints/multi_agent/four_stage_share_noise_50/inventory_std.npy")
MAS4N50_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_50/backlog_mean.npy")
MAS4N50_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_50/backlog_std.npy")
MAS4N50_customer_backlog_mean = np.load("checkpoints/multi_agent/four_stage_share_noise_50/customer_backlog_mean.npy")
MAS4N50_customer_backlog_std = np.load("checkpoints/multi_agent/four_stage_share_noise_50/customer_backlog_std.npy")
MAS4N50_profit = np.load("checkpoints/multi_agent/four_stage_share_noise_50/profit.npy")

#%% Load CC Rl Data
CC4_results = np.load("checkpoints/cc_agent/four_stage/results.npy")
CC4_time = np.load("checkpoints/cc_agent/four_stage/time.npy")
CC4_reward_mean = np.load("checkpoints/cc_agent/four_stage/reward_mean.npy")
CC4_reward_std = np.load("checkpoints/cc_agent/four_stage/reward_std.npy")
CC4_inventory_mean = np.load("checkpoints/cc_agent/four_stage/inventory_mean.npy")
CC4_inventory_std = np.load("checkpoints/cc_agent/four_stage/inventory_std.npy")
CC4_backlog_mean = np.load("checkpoints/cc_agent/four_stage/backlog_mean.npy")
CC4_backlog_std = np.load("checkpoints/cc_agent/four_stage/backlog_std.npy")
CC4_customer_backlog_mean = np.load("checkpoints/cc_agent/four_stage/customer_backlog_mean.npy")
CC4_customer_backlog_std = np.load("checkpoints/cc_agent/four_stage/customer_backlog_std.npy")
CC4_profit = np.load("checkpoints/cc_agent/four_stage/profit.npy")

CC4I_results = np.load("checkpoints/cc_agent/four_stage_independent/results.npy")
CC4I_time = np.load("checkpoints/cc_agent/four_stage_independent/time.npy")
CC4I_reward_mean = np.load("checkpoints/cc_agent/four_stage_independent/reward_mean.npy")
CC4I_reward_std = np.load("checkpoints/cc_agent/four_stage_independent/reward_std.npy")
CC4i_inventory_mean = np.load("checkpoints/cc_agent/four_stage_independent/inventory_mean.npy")
CC4I_inventory_std = np.load("checkpoints/cc_agent/four_stage_independent/inventory_std.npy")
CC4I_backlog_mean = np.load("checkpoints/cc_agent/four_stage_independent/backlog_mean.npy")
CC4I_backlog_std = np.load("checkpoints/cc_agent/four_stage_independent/backlog_std.npy")
CC4I_customer_backlog_mean = np.load("checkpoints/cc_agent/four_stage_independent/customer_backlog_mean.npy")
CC4I_customer_backlog_std = np.load("checkpoints/cc_agent/four_stage_independent/customer_backlog_std.npy")
CC4I_profit = np.load("checkpoints/cc_agent/four_stage_independent/profit.npy")

CC2_results = np.load("checkpoints/cc_agent/two_stage/results.npy")
CC2_time = np.load("checkpoints/cc_agent/two_stage/time.npy")
CC2_reward_mean = np.load("checkpoints/cc_agent/two_stage/reward_mean.npy")
CC2_reward_std = np.load("checkpoints/cc_agent/two_stage/reward_std.npy")
CC2_inventory_mean = np.load("checkpoints/cc_agent/two_stage/inventory_mean.npy")
CC2_inventory_std = np.load("checkpoints/cc_agent/two_stage/inventory_std.npy")
CC2_backlog_mean = np.load("checkpoints/cc_agent/two_stage/backlog_mean.npy")
CC2_backlog_std = np.load("checkpoints/cc_agent/two_stage/backlog_std.npy")
CC2_customer_backlog_mean = np.load("checkpoints/cc_agent/two_stage/customer_backlog_mean.npy")
CC2_customer_backlog_std = np.load("checkpoints/cc_agent/two_stage/customer_backlog_std.npy")
CC2_profit = np.load("checkpoints/cc_agent/two_stage/profit.npy")

CC8_results = np.load("checkpoints/cc_agent/eight_stage/results.npy")
CC8_time = np.load("checkpoints/cc_agent/eight_stage/time.npy")
CC8_reward_mean = np.load("checkpoints/cc_agent/eight_stage/reward_mean.npy")
CC8_reward_std = np.load("checkpoints/cc_agent/eight_stage/reward_std.npy")
CC8_inventory_mean = np.load("checkpoints/cc_agent/eight_stage/inventory_mean.npy")
CC8_inventory_std = np.load("checkpoints/cc_agent/eight_stage/inventory_std.npy")
CC8_backlog_mean = np.load("checkpoints/cc_agent/eight_stage/backlog_mean.npy")
CC8_backlog_std = np.load("checkpoints/cc_agent/eight_stage/backlog_std.npy")
CC8_customer_backlog_mean = np.load("checkpoints/cc_agent/eight_stage/customer_backlog_mean.npy")
CC8_customer_backlog_std = np.load("checkpoints/cc_agent/eight_stage/customer_backlog_std.npy")
CC8_profit = np.load("checkpoints/cc_agent/eight_stage/profit.npy")

CC4N2_results = np.load("checkpoints/cc_agent/four_stage_noise_2/results.npy")
CC4N2_time = np.load("checkpoints/cc_agent/four_stage_noise_2/time.npy")
CC4N2_reward_mean = np.load("checkpoints/cc_agent/four_stage_noise_2/reward_mean.npy")
CC4N2_reward_std = np.load("checkpoints/cc_agent/four_stage_noise_2/reward_std.npy")
CC4N2_inventory_mean = np.load("checkpoints/cc_agent/four_stage_noise_2/inventory_mean.npy")
CC4N2_inventory_std = np.load("checkpoints/cc_agent/four_stage_noise_2/inventory_std.npy")
CC4N2_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_2/backlog_mean.npy")
CC4N2_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_2/backlog_std.npy")
CC4N2_customer_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_2/customer_backlog_mean.npy")
CC4N2_customer_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_2/customer_backlog_std.npy")
CC4N2_profit = np.load("checkpoints/cc_agent/four_stage_noise_2/profit.npy")

CC4N5_results = np.load("checkpoints/cc_agent/four_stage_noise_5/results.npy")
CC4N5_time = np.load("checkpoints/cc_agent/four_stage_noise_5/time.npy")
CC4N5_reward_mean = np.load("checkpoints/cc_agent/four_stage_noise_5/reward_mean.npy")
CC4N5_reward_std = np.load("checkpoints/cc_agent/four_stage_noise_5/reward_std.npy")
CC4N5_inventory_mean = np.load("checkpoints/cc_agent/four_stage_noise_5/inventory_mean.npy")
CC4N5_inventory_std = np.load("checkpoints/cc_agent/four_stage_noise_5/inventory_std.npy")
CC4N5_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_5/backlog_mean.npy")
CC4N5_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_5/backlog_std.npy")
CC4N5_customer_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_5/customer_backlog_mean.npy")
CC4N5_customer_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_5/customer_backlog_std.npy")
CC4N5_profit = np.load("checkpoints/cc_agent/four_stage_noise_5/profit.npy")

CC4N10_results = np.load("checkpoints/cc_agent/four_stage_noise_10/results.npy")
CC4N10_time = np.load("checkpoints/cc_agent/four_stage_noise_10/time.npy")
CC4N10_reward_mean = np.load("checkpoints/cc_agent/four_stage_noise_10/reward_mean.npy")
CC4N10_reward_std = np.load("checkpoints/cc_agent/four_stage_noise_10/reward_std.npy")
CC4N10_inventory_mean = np.load("checkpoints/cc_agent/four_stage_noise_10/inventory_mean.npy")
CC4N10_inventory_std = np.load("checkpoints/cc_agent/four_stage_noise_10/inventory_std.npy")
CC4N10_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_10/backlog_mean.npy")
CC4N10_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_10/backlog_std.npy")
CC4N10_customer_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_10/customer_backlog_mean.npy")
CC4N10_customer_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_10/customer_backlog_std.npy")
CC4N10_profit = np.load("checkpoints/cc_agent/four_stage_noise_10/profit.npy")

CC4N20_results = np.load("checkpoints/cc_agent/four_stage_noise_20/results.npy")
CC4N20_time = np.load("checkpoints/cc_agent/four_stage_noise_20/time.npy")
CC4N20_reward_mean = np.load("checkpoints/cc_agent/four_stage_noise_20/reward_mean.npy")
CC4N20_reward_std = np.load("checkpoints/cc_agent/four_stage_noise_20/reward_std.npy")
CC4N20_inventory_mean = np.load("checkpoints/cc_agent/four_stage_noise_20/inventory_mean.npy")
CC4N20_inventory_std = np.load("checkpoints/cc_agent/four_stage_noise_20/inventory_std.npy")
CC4N20_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_20/backlog_mean.npy")
CC4N20_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_20/backlog_std.npy")
CC4N20_customer_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_20/customer_backlog_mean.npy")
CC4N20_customer_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_20/customer_backlog_std.npy")
CC4N20_profit = np.load("checkpoints/cc_agent/four_stage_noise_20/profit.npy")

CC4N50_results = np.load("checkpoints/cc_agent/four_stage_noise_50/results.npy")
CC4N50_time = np.load("checkpoints/cc_agent/four_stage_noise_50/time.npy")
CC4N50_reward_mean = np.load("checkpoints/cc_agent/four_stage_noise_50/reward_mean.npy")
CC4N50_reward_std = np.load("checkpoints/cc_agent/four_stage_noise_50/reward_std.npy")
CC4N50_inventory_mean = np.load("checkpoints/cc_agent/four_stage_noise_50/inventory_mean.npy")
CC4N50_inventory_std = np.load("checkpoints/cc_agent/four_stage_noise_50/inventory_std.npy")
CC4N50_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_50/backlog_mean.npy")
CC4N50_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_50/backlog_std.npy")
CC4N50_customer_backlog_mean = np.load("checkpoints/cc_agent/four_stage_noise_50/customer_backlog_mean.npy")
CC4N50_customer_backlog_std = np.load("checkpoints/cc_agent/four_stage_noise_50/customer_backlog_std.npy")
CC4N50_profit = np.load("checkpoints/cc_agent/four_stage_noise_50/profit.npy")
#%% Load DFO Data
DFO4_reward_mean = np.load("checkpoints/single_agent/four_stage/dfo_mean.npy")
DFO4_reward_std = np.load("checkpoints/single_agent/four_stage/dfo_std.npy")

DFO2_reward_mean = np.load("checkpoints/single_agent/two_stage/dfo_mean.npy")
DFO2_reward_std = np.load("checkpoints/single_agent/two_stage/dfo_std.npy")

DFO8_reward_mean = np.load("checkpoints/single_agent/eight_stage/dfo_mean.npy")
DFO8_reward_std = np.load("checkpoints/single_agent/eight_stage/dfo_std.npy")

DFO4N2_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_2/dfo_mean.npy")
DFO4N2_reward_std = np.load("checkpoints/single_agent/four_stage_noise_2/dfo_std.npy")

DFO4N5_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_5/dfo_mean.npy")
DFO4N5_reward_std = np.load("checkpoints/single_agent/four_stage_noise_5/dfo_std.npy")

DFO4N10_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_10/dfo_mean.npy")
DFO4N10_reward_std = np.load("checkpoints/single_agent/four_stage_noise_10/dfo_std.npy")

DFO4N20_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_20/dfo_mean.npy")
DFO4N20_reward_std = np.load("checkpoints/single_agent/four_stage_noise_20/dfo_std.npy")

DFO4N50_reward_mean = np.load("checkpoints/single_agent/four_stage_noise_50/dfo_mean.npy")
DFO4N50_reward_std = np.load("checkpoints/single_agent/four_stage_noise_50/dfo_std.npy")

#%% Load Oracle Data
OR4_reward_mean = np.load("LP_results/four_stage/Oracle/reward_mean.npy")
OR4_reward_std = np.load("LP_results/four_stage/Oracle/reward_std.npy")
OR4_inventory_mean = np.load("LP_results/four_stage/Oracle/inventory_mean.npy")
OR4_inventory_std = np.load("LP_results/four_stage/Oracle/inventory_std.npy")
OR4_backlog_mean = np.load("LP_results/four_stage/Oracle/backlog_mean.npy")
OR4_backlog_std = np.load("LP_results/four_stage/Oracle/backlog_std.npy")
OR4_customer_backlog_mean = np.load("LP_results/four_stage/Oracle/customer_backlog_mean.npy")
OR4_customer_backlog_std = np.load("LP_results/four_stage/Oracle/customer_backlog_std.npy")
OR4_profit = np.load("LP_results/four_stage/Oracle/profit.npy")

OR2_reward_mean = np.load("LP_results/two_stage/Oracle/reward_mean.npy")
OR2_reward_std = np.load("LP_results/two_stage/Oracle/reward_std.npy")
OR2_inventory_mean = np.load("LP_results/two_stage/Oracle/inventory_mean.npy")
OR2_inventory_std = np.load("LP_results/two_stage/Oracle/inventory_std.npy")
OR2_backlog_mean = np.load("LP_results/two_stage/Oracle/backlog_mean.npy")
OR2_backlog_std = np.load("LP_results/two_stage/Oracle/backlog_std.npy")
OR2_customer_backlog_mean = np.load("LP_results/two_stage/Oracle/customer_backlog_mean.npy")
OR2_customer_backlog_std = np.load("LP_results/two_stage/Oracle/customer_backlog_std.npy")
OR2_profit = np.load("LP_results/two_stage/Oracle/profit.npy")

OR8_reward_mean = np.load("LP_results/eight_stage/Oracle/reward_mean.npy")
OR8_reward_std = np.load("LP_results/eight_stage/Oracle/reward_std.npy")
OR8_inventory_mean = np.load("LP_results/eight_stage/Oracle/inventory_mean.npy")
OR8_inventory_std = np.load("LP_results/eight_stage/Oracle/inventory_std.npy")
OR8_backlog_mean = np.load("LP_results/eight_stage/Oracle/backlog_mean.npy")
OR8_backlog_std = np.load("LP_results/eight_stage/Oracle/backlog_std.npy")
OR8_customer_backlog_mean = np.load("LP_results/eight_stage/Oracle/customer_backlog_mean.npy")
OR8_customer_backlog_std = np.load("LP_results/eight_stage/Oracle/customer_backlog_std.npy")
OR8_profit = np.load("LP_results/eight_stage/Oracle/profit.npy")

OR4N2_reward_mean = np.load("LP_results/four_stage_noise_2/Oracle/reward_mean.npy")
OR4N2_reward_std = np.load("LP_results/four_stage_noise_2/Oracle/reward_std.npy")
OR4N2_inventory_mean = np.load("LP_results/four_stage_noise_2/Oracle/inventory_mean.npy")
OR4N2_inventory_std = np.load("LP_results/four_stage_noise_2/Oracle/inventory_std.npy")
OR4N2_backlog_mean = np.load("LP_results/four_stage_noise_2/Oracle/backlog_mean.npy")
OR4N2_backlog_std = np.load("LP_results/four_stage_noise_2/Oracle/backlog_std.npy")
OR4N2_customer_backlog_mean = np.load("LP_results/four_stage_noise_2/Oracle/customer_backlog_mean.npy")
OR4N2_customer_backlog_std = np.load("LP_results/four_stage_noise_2/Oracle/customer_backlog_std.npy")
OR4N2_profit = np.load("LP_results/four_stage_noise_2/Oracle/profit.npy")

OR4N5_reward_mean = np.load("LP_results/four_stage_noise_5/Oracle/reward_mean.npy")
OR4N5_reward_std = np.load("LP_results/four_stage_noise_5/Oracle/reward_std.npy")
OR4N5_inventory_mean = np.load("LP_results/four_stage_noise_5/Oracle/inventory_mean.npy")
OR4N5_inventory_std = np.load("LP_results/four_stage_noise_5/Oracle/inventory_std.npy")
OR4N5_backlog_mean = np.load("LP_results/four_stage_noise_5/Oracle/backlog_mean.npy")
OR4N5_backlog_std = np.load("LP_results/four_stage_noise_5/Oracle/backlog_std.npy")
OR4N5_customer_backlog_mean = np.load("LP_results/four_stage_noise_5/Oracle/customer_backlog_mean.npy")
OR4N5_customer_backlog_std = np.load("LP_results/four_stage_noise_5/Oracle/customer_backlog_std.npy")
OR4N5_profit = np.load("LP_results/four_stage_noise_5/Oracle/profit.npy")

OR4N10_reward_mean = np.load("LP_results/four_stage_noise_10/Oracle/reward_mean.npy")
OR4N10_reward_std = np.load("LP_results/four_stage_noise_10/Oracle/reward_std.npy")
OR4N10_inventory_mean = np.load("LP_results/four_stage_noise_10/Oracle/inventory_mean.npy")
OR4N10_inventory_std = np.load("LP_results/four_stage_noise_10/Oracle/inventory_std.npy")
OR4N10_backlog_mean = np.load("LP_results/four_stage_noise_10/Oracle/backlog_mean.npy")
OR4N10_backlog_std = np.load("LP_results/four_stage_noise_10/Oracle/backlog_std.npy")
OR4N10_customer_backlog_mean = np.load("LP_results/four_stage_noise_10/Oracle/customer_backlog_mean.npy")
OR4N10_customer_backlog_std = np.load("LP_results/four_stage_noise_10/Oracle/customer_backlog_std.npy")
OR4N10_profit = np.load("LP_results/four_stage_noise_10/Oracle/profit.npy")

OR4N20_reward_mean = np.load("LP_results/four_stage_noise_20/Oracle/reward_mean.npy")
OR4N20_reward_std = np.load("LP_results/four_stage_noise_20/Oracle/reward_std.npy")
OR4N20_inventory_mean = np.load("LP_results/four_stage_noise_20/Oracle/inventory_mean.npy")
OR4N20_inventory_std = np.load("LP_results/four_stage_noise_20/Oracle/inventory_std.npy")
OR4N20_backlog_mean = np.load("LP_results/four_stage_noise_20/Oracle/backlog_mean.npy")
OR4N20_backlog_std = np.load("LP_results/four_stage_noise_20/Oracle/backlog_std.npy")
OR4N20_customer_backlog_mean = np.load("LP_results/four_stage_noise_20/Oracle/customer_backlog_mean.npy")
OR4N20_customer_backlog_std = np.load("LP_results/four_stage_noise_20/Oracle/customer_backlog_std.npy")
OR4N20_profit = np.load("LP_results/four_stage_noise_20/Oracle/profit.npy")

OR4N50_reward_mean = np.load("LP_results/four_stage_noise_50/Oracle/reward_mean.npy")
OR4N50_reward_std = np.load("LP_results/four_stage_noise_50/Oracle/reward_std.npy")
OR4N50_inventory_mean = np.load("LP_results/four_stage_noise_50/Oracle/inventory_mean.npy")
OR4N50_inventory_std = np.load("LP_results/four_stage_noise_50/Oracle/inventory_std.npy")
OR4N50_backlog_mean = np.load("LP_results/four_stage_noise_50/Oracle/backlog_mean.npy")
OR4N50_backlog_std = np.load("LP_results/four_stage_noise_50/Oracle/backlog_std.npy")
OR4N50_customer_backlog_mean = np.load("LP_results/four_stage_noise_50/Oracle/customer_backlog_mean.npy")
OR4N50_customer_backlog_std = np.load("LP_results/four_stage_noise_50/Oracle/customer_backlog_std.npy")
OR4N50_profit = np.load("LP_results/four_stage_noise_50/Oracle/profit.npy")

#%% Load SHLP Data
SHLP4_time = np.load("LP_results/four_stage/SHLP/time.npy")
SHLP4_reward_mean = np.load("LP_results/four_stage/SHLP/reward_mean.npy")
SHLP4_reward_std = np.load("LP_results/four_stage/SHLP/reward_std.npy")
SHLP4_inventory_mean = np.load("LP_results/four_stage/SHLP/inventory_mean.npy")
SHLP4_inventory_std = np.load("LP_results/four_stage/SHLP/inventory_std.npy")
SHLP4_backlog_mean = np.load("LP_results/four_stage/SHLP/backlog_mean.npy")
SHLP4_backlog_std = np.load("LP_results/four_stage/SHLP/backlog_std.npy")
SHLP4_customer_backlog_mean = np.load("LP_results/four_stage/SHLP/customer_backlog_mean.npy")
SHLP4_customer_backlog_std = np.load("LP_results/four_stage/SHLP/customer_backlog_std.npy")
SHLP4_profit = np.load("LP_results/four_stage/SHLP/profit.npy")

SHLP2_time = np.load("LP_results/two_stage/SHLP/time.npy")
SHLP2_reward_mean = np.load("LP_results/two_stage/SHLP/reward_mean.npy")
SHLP2_reward_std = np.load("LP_results/two_stage/SHLP/reward_std.npy")
SHLP2_inventory_mean = np.load("LP_results/two_stage/SHLP/inventory_mean.npy")
SHLP2_inventory_std = np.load("LP_results/two_stage/SHLP/inventory_std.npy")
SHLP2_backlog_mean = np.load("LP_results/two_stage/SHLP/backlog_mean.npy")
SHLP2_backlog_std = np.load("LP_results/two_stage/SHLP/backlog_std.npy")
SHLP2_customer_backlog_mean = np.load("LP_results/two_stage/SHLP/customer_backlog_mean.npy")
SHLP2_customer_backlog_std = np.load("LP_results/two_stage/SHLP/customer_backlog_std.npy")
SHLP2_profit = np.load("LP_results/two_stage/SHLP/profit.npy")

SHLP8_time = np.load("LP_results/eight_stage/SHLP/time.npy")
SHLP8_reward_mean = np.load("LP_results/eight_stage/SHLP/reward_mean.npy")
SHLP8_reward_std = np.load("LP_results/eight_stage/SHLP/reward_std.npy")
SHLP8_inventory_mean = np.load("LP_results/eight_stage/SHLP/inventory_mean.npy")
SHLP8_inventory_std = np.load("LP_results/eight_stage/SHLP/inventory_std.npy")
SHLP8_backlog_mean = np.load("LP_results/eight_stage/SHLP/backlog_mean.npy")
SHLP8_backlog_std = np.load("LP_results/eight_stage/SHLP/backlog_std.npy")
SHLP8_customer_backlog_mean = np.load("LP_results/eight_stage/SHLP/customer_backlog_mean.npy")
SHLP8_customer_backlog_std = np.load("LP_results/eight_stage/SHLP/customer_backlog_std.npy")
SHLP8_profit = np.load("LP_results/eight_stage/SHLP/profit.npy")

SHLP4N2_time = np.load("LP_results/four_stage_noise_2/SHLP/time.npy")
SHLP4N2_reward_mean = np.load("LP_results/four_stage_noise_2/SHLP/reward_mean.npy")
SHLP4N2_reward_std = np.load("LP_results/four_stage_noise_2/SHLP/reward_std.npy")
SHLP4N2_inventory_mean = np.load("LP_results/four_stage_noise_2/SHLP/inventory_mean.npy")
SHLP4N2_inventory_std = np.load("LP_results/four_stage_noise_2/SHLP/inventory_std.npy")
SHLP4N2_backlog_mean = np.load("LP_results/four_stage_noise_2/SHLP/backlog_mean.npy")
SHLP4N2_backlog_std = np.load("LP_results/four_stage_noise_2/SHLP/backlog_std.npy")
SHLP4N2_customer_backlog_mean = np.load("LP_results/four_stage_noise_2/SHLP/customer_backlog_mean.npy")
SHLP4N2_customer_backlog_std = np.load("LP_results/four_stage_noise_2/SHLP/customer_backlog_std.npy")
SHLP4N2_profit = np.load("LP_results/four_stage_noise_2/SHLP/profit.npy")

SHLP4N5_time = np.load("LP_results/four_stage_noise_5/SHLP/time.npy")
SHLP4N5_reward_mean = np.load("LP_results/four_stage_noise_5/SHLP/reward_mean.npy")
SHLP4N5_reward_std = np.load("LP_results/four_stage_noise_5/SHLP/reward_std.npy")
SHLP4N5_inventory_mean = np.load("LP_results/four_stage_noise_5/SHLP/inventory_mean.npy")
SHLP4N5_inventory_std = np.load("LP_results/four_stage_noise_5/SHLP/inventory_std.npy")
SHLP4N5_backlog_mean = np.load("LP_results/four_stage_noise_5/SHLP/backlog_mean.npy")
SHLP4N5_backlog_std = np.load("LP_results/four_stage_noise_5/SHLP/backlog_std.npy")
SHLP4N5_customer_backlog_mean = np.load("LP_results/four_stage_noise_5/SHLP/customer_backlog_mean.npy")
SHLP4N5_customer_backlog_std = np.load("LP_results/four_stage_noise_5/SHLP/customer_backlog_std.npy")
SHLP4N5_profit = np.load("LP_results/four_stage_noise_5/SHLP/profit.npy")

SHLP4N10_time = np.load("LP_results/four_stage_noise_10/SHLP/time.npy")
SHLP4N10_reward_mean = np.load("LP_results/four_stage_noise_10/SHLP/reward_mean.npy")
SHLP4N10_reward_std = np.load("LP_results/four_stage_noise_10/SHLP/reward_std.npy")
SHLP4N10_inventory_mean = np.load("LP_results/four_stage_noise_10/SHLP/inventory_mean.npy")
SHLP4N10_inventory_std = np.load("LP_results/four_stage_noise_10/SHLP/inventory_std.npy")
SHLP4N10_backlog_mean = np.load("LP_results/four_stage_noise_10/SHLP/backlog_mean.npy")
SHLP4N10_backlog_std = np.load("LP_results/four_stage_noise_10/SHLP/backlog_std.npy")
SHLP4N10_customer_backlog_mean = np.load("LP_results/four_stage_noise_10/SHLP/customer_backlog_mean.npy")
SHLP4N10_customer_backlog_std = np.load("LP_results/four_stage_noise_10/SHLP/customer_backlog_std.npy")
SHLP4N10_profit = np.load("LP_results/four_stage_noise_10/SHLP/profit.npy")

SHLP4N20_time = np.load("LP_results/four_stage_noise_20/SHLP/time.npy")
SHLP4N20_reward_mean = np.load("LP_results/four_stage_noise_20/SHLP/reward_mean.npy")
SHLP4N20_reward_std = np.load("LP_results/four_stage_noise_20/SHLP/reward_std.npy")
SHLP4N20_inventory_mean = np.load("LP_results/four_stage_noise_20/SHLP/inventory_mean.npy")
SHLP4N20_inventory_std = np.load("LP_results/four_stage_noise_20/SHLP/inventory_std.npy")
SHLP4N20_backlog_mean = np.load("LP_results/four_stage_noise_20/SHLP/backlog_mean.npy")
SHLP4N20_backlog_std = np.load("LP_results/four_stage_noise_20/SHLP/backlog_std.npy")
SHLP4N20_customer_backlog_mean = np.load("LP_results/four_stage_noise_20/SHLP/customer_backlog_mean.npy")
SHLP4N20_customer_backlog_std = np.load("LP_results/four_stage_noise_20/SHLP/customer_backlog_std.npy")
SHLP4N20_profit = np.load("LP_results/four_stage_noise_20/SHLP/profit.npy")

SHLP4N50_time = np.load("LP_results/four_stage_noise_50/SHLP/time.npy")
SHLP4N50_reward_mean = np.load("LP_results/four_stage_noise_50/SHLP/reward_mean.npy")
SHLP4N50_reward_std = np.load("LP_results/four_stage_noise_50/SHLP/reward_std.npy")
SHLP4N50_inventory_mean = np.load("LP_results/four_stage_noise_50/SHLP/inventory_mean.npy")
SHLP4N50_inventory_std = np.load("LP_results/four_stage_noise_50/SHLP/inventory_std.npy")
SHLP4N50_backlog_mean = np.load("LP_results/four_stage_noise_50/SHLP/backlog_mean.npy")
SHLP4N50_backlog_std = np.load("LP_results/four_stage_noise_50/SHLP/backlog_std.npy")
SHLP4N50_customer_backlog_mean = np.load("LP_results/four_stage_noise_50/SHLP/customer_backlog_mean.npy")
SHLP4N50_customer_backlog_std = np.load("LP_results/four_stage_noise_50/SHLP/customer_backlog_std.npy")
SHLP4N50_profit = np.load("LP_results/four_stage_noise_50/SHLP/profit.npy")

#%% Load SHLP Data
DecLP4_time = np.load("LP_results/four_stage/DecLP/time.npy")
DecLP4_reward_mean = np.load("LP_results/four_stage/DecLP/reward_mean.npy")
DecLP4_reward_std = np.load("LP_results/four_stage/DecLP/reward_std.npy")
DecLP4_inventory_mean = np.load("LP_results/four_stage/DecLP/inventory_mean.npy")
DecLP4_inventory_std = np.load("LP_results/four_stage/DecLP/inventory_std.npy")
DecLP4_backlog_mean = np.load("LP_results/four_stage/DecLP/backlog_mean.npy")
DecLP4_backlog_std = np.load("LP_results/four_stage/DecLP/backlog_std.npy")
DecLP4_customer_backlog_mean = np.load("LP_results/four_stage/DecLP/customer_backlog_mean.npy")
DecLP4_customer_backlog_std = np.load("LP_results/four_stage/DecLP/customer_backlog_std.npy")
DecLP4_profit = np.load("LP_results/four_stage/DecLP/profit.npy")

DecLP2_time = np.load("LP_results/two_stage/DecLP/time.npy")
DecLP2_reward_mean = np.load("LP_results/two_stage/DecLP/reward_mean.npy")
DecLP2_reward_std = np.load("LP_results/two_stage/DecLP/reward_std.npy")
DecLP2_inventory_mean = np.load("LP_results/two_stage/DecLP/inventory_mean.npy")
DecLP2_inventory_std = np.load("LP_results/two_stage/DecLP/inventory_std.npy")
DecLP2_backlog_mean = np.load("LP_results/two_stage/DecLP/backlog_mean.npy")
DecLP2_backlog_std = np.load("LP_results/two_stage/DecLP/backlog_std.npy")
DecLP2_customer_backlog_mean = np.load("LP_results/two_stage/DecLP/customer_backlog_mean.npy")
DecLP2_customer_backlog_std = np.load("LP_results/two_stage/DecLP/customer_backlog_std.npy")
DecLP2_profit = np.load("LP_results/two_stage/DecLP/profit.npy")

DecLP8_time = np.load("LP_results/eight_stage/DecLP/time.npy")
DecLP8_reward_mean = np.load("LP_results/eight_stage/DecLP/reward_mean.npy")
DecLP8_reward_std = np.load("LP_results/eight_stage/DecLP/reward_std.npy")
DecLP8_inventory_mean = np.load("LP_results/eight_stage/DecLP/inventory_mean.npy")
DecLP8_inventory_std = np.load("LP_results/eight_stage/DecLP/inventory_std.npy")
DecLP8_backlog_mean = np.load("LP_results/eight_stage/DecLP/backlog_mean.npy")
DecLP8_backlog_std = np.load("LP_results/eight_stage/DecLP/backlog_std.npy")
DecLP8_customer_backlog_mean = np.load("LP_results/eight_stage/DecLP/customer_backlog_mean.npy")
DecLP8_customer_backlog_std = np.load("LP_results/eight_stage/DecLP/customer_backlog_std.npy")
DecLP8_profit = np.load("LP_results/eight_stage/DecLP/profit.npy")

DecLP4N2_time = np.load("LP_results/four_stage_noise_2/DecLP/time.npy")
DecLP4N2_reward_mean = np.load("LP_results/four_stage_noise_2/DecLP/reward_mean.npy")
DecLP4N2_reward_std = np.load("LP_results/four_stage_noise_2/DecLP/reward_std.npy")
DecLP4N2_inventory_mean = np.load("LP_results/four_stage_noise_2/DecLP/inventory_mean.npy")
DecLP4N2_inventory_std = np.load("LP_results/four_stage_noise_2/DecLP/inventory_std.npy")
DecLP4N2_backlog_mean = np.load("LP_results/four_stage_noise_2/DecLP/backlog_mean.npy")
DecLP4N2_backlog_std = np.load("LP_results/four_stage_noise_2/DecLP/backlog_std.npy")
DecLP4N2_customer_backlog_mean = np.load("LP_results/four_stage_noise_2/DecLP/customer_backlog_mean.npy")
DecLP4N2_customer_backlog_std = np.load("LP_results/four_stage_noise_2/DecLP/customer_backlog_std.npy")
DecLP4N2_profit = np.load("LP_results/four_stage_noise_2/DecLP/profit.npy")

DecLP4N5_time = np.load("LP_results/four_stage_noise_5/DecLP/time.npy")
DecLP4N5_reward_mean = np.load("LP_results/four_stage_noise_5/DecLP/reward_mean.npy")
DecLP4N5_reward_std = np.load("LP_results/four_stage_noise_5/DecLP/reward_std.npy")
DecLP4N5_inventory_mean = np.load("LP_results/four_stage_noise_5/DecLP/inventory_mean.npy")
DecLP4N5_inventory_std = np.load("LP_results/four_stage_noise_5/DecLP/inventory_std.npy")
DecLP4N5_backlog_mean = np.load("LP_results/four_stage_noise_5/DecLP/backlog_mean.npy")
DecLP4N5_backlog_std = np.load("LP_results/four_stage_noise_5/DecLP/backlog_std.npy")
DecLP4N5_customer_backlog_mean = np.load("LP_results/four_stage_noise_5/DecLP/customer_backlog_mean.npy")
DecLP4N5_customer_backlog_std = np.load("LP_results/four_stage_noise_5/DecLP/customer_backlog_std.npy")
DecLP4N5_profit = np.load("LP_results/four_stage_noise_5/DecLP/profit.npy")

DecLP4N10_time = np.load("LP_results/four_stage_noise_10/DecLP/time.npy")
DecLP4N10_reward_mean = np.load("LP_results/four_stage_noise_10/DecLP/reward_mean.npy")
DecLP4N10_reward_std = np.load("LP_results/four_stage_noise_10/DecLP/reward_std.npy")
DecLP4N10_inventory_mean = np.load("LP_results/four_stage_noise_10/DecLP/inventory_mean.npy")
DecLP4N10_inventory_std = np.load("LP_results/four_stage_noise_10/DecLP/inventory_std.npy")
DecLP4N10_backlog_mean = np.load("LP_results/four_stage_noise_10/DecLP/backlog_mean.npy")
DecLP4N10_backlog_std = np.load("LP_results/four_stage_noise_10/DecLP/backlog_std.npy")
DecLP4N10_customer_backlog_mean = np.load("LP_results/four_stage_noise_10/DecLP/customer_backlog_mean.npy")
DecLP4N10_customer_backlog_std = np.load("LP_results/four_stage_noise_10/DecLP/customer_backlog_std.npy")
DecLP4N10_profit = np.load("LP_results/four_stage_noise_10/DecLP/profit.npy")

DecLP4N20_time = np.load("LP_results/four_stage_noise_20/DecLP/time.npy")
DecLP4N20_reward_mean = np.load("LP_results/four_stage_noise_20/DecLP/reward_mean.npy")
DecLP4N20_reward_std = np.load("LP_results/four_stage_noise_20/DecLP/reward_std.npy")
DecLP4N20_inventory_mean = np.load("LP_results/four_stage_noise_20/DecLP/inventory_mean.npy")
DecLP4N20_inventory_std = np.load("LP_results/four_stage_noise_20/DecLP/inventory_std.npy")
DecLP4N20_backlog_mean = np.load("LP_results/four_stage_noise_20/DecLP/backlog_mean.npy")
DecLP4N20_backlog_std = np.load("LP_results/four_stage_noise_20/DecLP/backlog_std.npy")
DecLP4N20_customer_backlog_mean = np.load("LP_results/four_stage_noise_20/DecLP/customer_backlog_mean.npy")
DecLP4N20_customer_backlog_std = np.load("LP_results/four_stage_noise_20/DecLP/customer_backlog_std.npy")
DecLP4N20_profit = np.load("LP_results/four_stage_noise_20/DecLP/profit.npy")

DecLP4N50_time = np.load("LP_results/four_stage_noise_50/DecLP/time.npy")
DecLP4N50_reward_mean = np.load("LP_results/four_stage_noise_50/DecLP/reward_mean.npy")
DecLP4N50_reward_std = np.load("LP_results/four_stage_noise_50/DecLP/reward_std.npy")
DecLP4N50_inventory_mean = np.load("LP_results/four_stage_noise_50/DecLP/inventory_mean.npy")
DecLP4N50_inventory_std = np.load("LP_results/four_stage_noise_50/DecLP/inventory_std.npy")
DecLP4N50_backlog_mean = np.load("LP_results/four_stage_noise_50/DecLP/backlog_mean.npy")
DecLP4N50_backlog_std = np.load("LP_results/four_stage_noise_50/DecLP/backlog_std.npy")
DecLP4N50_customer_backlog_mean = np.load("LP_results/four_stage_noise_50/DecLP/customer_backlog_mean.npy")
DecLP4N50_customer_backlog_std = np.load("LP_results/four_stage_noise_50/DecLP/customer_backlog_std.npy")
DecLP4N50_profit = np.load("LP_results/four_stage_noise_50/DecLP/profit.npy")
